networks:
  fakenews-net:
    driver: bridge

volumes:
  kafka-data:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    networks:
      - fakenews-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    networks:
      - fakenews-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-init
    networks:
      - fakenews-net
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Waiting for Kafka...'
      sleep 20
      kafka-topics --bootstrap-server kafka:29092 \
        --create \
        --if-not-exists \
        --topic news-stream \
        --partitions 1 \
        --replication-factor 1
      echo 'Kafka topic news-stream is ready.'
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - fakenews-net
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: fakenews-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  reddit-producer:
    build:
      context: ./pipeline
    container_name: reddit-producer
    networks:
      - fakenews-net
    depends_on:
      - kafka-init
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      KAFKA_TOPIC: news-stream
      FETCH_INTERVAL_MS: 10000

  spark-master:
    image: spark:3.5.1
    container_name: spark-master
    networks:
      - fakenews-net
    depends_on:
      - kafka
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./pipeline:/app/pipeline
      - ./outputs:/app/outputs
      - ./data:/app/data

  spark-worker:
    image: spark:3.5.1
    container_name: spark-worker
    networks:
      - fakenews-net
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./pipeline:/app/pipeline
      - ./outputs:/app/outputs
      - ./data:/app/data

  hbase:
    image: harisekhon/hbase
    container_name: hbase
    hostname: hbase
    networks:
      - fakenews-net
    ports:
      - "16010:16010"
      - "16000:16000"
      - "9090:9090"
      - "2182:2181"

  hbase-init:
    image: dajobe/hbase:latest
    container_name: hbase-init
    depends_on:
      - hbase
    networks:
      - fakenews-net
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "
      echo 'Waiting for HBase...' &&
      sleep 40 &&
      echo \"create_namespace 'default'\" | hbase shell -n || true &&
      echo \"create 'news_events', 'info'\" | hbase shell -n || true
      "
  nlp-service:
    build:
      context: ./nlp-service
    container_name: nlp-service
    networks:
      - fakenews-net
    ports:
      - "8000:8000"

  spark-consumer:
    image: spark:3.5.1
    container_name: spark-consumer
    networks:
      - fakenews-net
    depends_on:
      - spark-master
      - spark-worker
      - kafka-init
      - hbase
      - nlp-service
    volumes:
      - ./pipeline:/app/pipeline
      - ./outputs:/app/outputs
      - ./data:/app/data
    working_dir: /app/pipeline
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      KAFKA_TOPIC: news-stream
      NLP_SERVICE_URL: http://nlp-service:8000/classify
    command: >
      /bin/bash -c "
      echo 'Waiting for Spark, Kafka, HBase, and NLP service...' &&
      sleep 90 &&
      mkdir -p /tmp/.ivy2/cache &&
      /opt/spark/bin/spark-submit
      --class com.fakenews.spark.NewsSparkConsumer
      --master spark://spark-master:7077
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.hbase:hbase-client:1.2.6,org.apache.hbase:hbase-common:1.2.6
      target/reddit-fetcher-1.0-SNAPSHOT.jar
      "

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    networks:
      - fakenews-net
    depends_on:
      - hbase
    ports:
      - "8501:8501"
    environment:
      HBASE_HOST: hbase
      HBASE_PORT: 9090
      HBASE_TABLE: news_events
      REFRESH_SECONDS: 10